In [1]:
from IPython.display import display, Math
import numpy as np

# Inner Product

> 두 벡터 간 유사성을 구합니다.

In [15]:
inner_product = r"""
   \mathbf{a} \cdot \mathbf{b} = 
   \begin{bmatrix}
   a_1 \\
   a_2 \\
   a_3
   \end{bmatrix}
   \cdot
   \begin{bmatrix}
   b_1 \\
   b_2 \\
   b_3
   \end{bmatrix}
   = a_1 b_1 + a_2 b_2 + a_3 b_3
   = \sum_{i=1}^{n} a_i b_i
"""

display(Math(inner_product))

<IPython.core.display.Math object>

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

inner_product = np.dot(a, b)

print("Inner Product:\n", inner_product)

Inner Product:
 32


# Matrix Multiplication

> 벡터를 행렬로 확장하고, 하나의 행렬을 Transpose하고, 이를 Matmul 한 것이 Inner Product이다.

In [20]:
mat_mul = r"""
    \mathbf{a}^T \cdot \mathbf{b} =
    \begin{bmatrix} a_1 & a_2 & a_3 \end{bmatrix} \cdot
    \begin{bmatrix} b_1 \\ b_2 \\ b_3 \end{bmatrix}
    =
    \begin{bmatrix} a_1 b_1 + a_2 b_2 + a_3 b_3 \end{bmatrix}
"""

# Jupyter Notebook에서 LaTeX 수식 렌더링
display(Math(mat_mul))

<IPython.core.display.Math object>

In [19]:
a = np.array([[1, 2], [3, 4], [5, 6]])      # (3,2)
b = np.array([[7, 8], [9, 10], [11, 12]])   # (3,2)

inner_product = np.matmul(a.T, b)
print("Mat Mul:\n", inner_product)

Mat Mul:
 [[ 89  98]
 [116 128]]


# Outer Product

> 행 벡터와 열 벡터의 곱으로 외적곱 행렬을 만듭니다. 벡터를 행렬로 확장하기 위해 쓰이는 연산으로, feature vector와 weight vector 간 연산으로 weight metrix를 만들 때 사용됩니다.

In [13]:
outer_product = r"""
    \mathbf{a} \otimes \mathbf{b} =
    \begin{bmatrix}
    a_1 \\
    a_2 \\
    a_3
    \end{bmatrix}
    \otimes
    \begin{bmatrix}
    b_1 & b_2 & b_3
    \end{bmatrix} =
    \begin{bmatrix}
    a_1 b_1 & a_1 b_2 & a_1 b_3 \\
    a_2 b_1 & a_2 b_2 & a_2 b_3 \\
    a_3 b_1 & a_3 b_2 & a_3 b_3
    \end{bmatrix}
"""

display(Math(outer_product))

<IPython.core.display.Math object>

In [5]:
a = np.array([1, 2, 3])
b = np.array([[4], [5], [6]])

outer_product = np.outer(a, b)

print("Outer Product:\n", outer_product)

Outer Product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


# Cross Product

> 두 벡터가 이루는 평면에 수직(orthogonal)한 벡터를 생성합니다. 결과 벡터의 크기(길이)는 두 벡터가 이루는 평행사변형의 면적을 나타냅니다.

In [6]:
cross_product = r"""
    \mathbf{a} \times \mathbf{b} =
    \begin{bmatrix}
    a_2 b_3 - a_3 b_2 \\
    a_3 b_1 - a_1 b_3 \\
    a_1 b_2 - a_2 b_1
    \end{bmatrix}
"""

display(Math(cross_product))

<IPython.core.display.Math object>

In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

cross_product = np.cross(a, b)
print("Cross Product:\n", cross_product)

Cross Product:
 [-3  6 -3]


# Element-Wise Product (Hadamard Product)

> 같은 위치의 원소끼리 직접 곱하는 연산입니다. Activation Function 등에 사용됩니다.

In [10]:
element_wise_product = r"""
    \mathbf{A} \odot \mathbf{B} =
    \begin{bmatrix}
    a_{11} & a_{12} & a_{13} \\
    a_{21} & a_{22} & a_{23} \\
    a_{31} & a_{32} & a_{33}
    \end{bmatrix}
    \odot
    \begin{bmatrix}
    b_{11} & b_{12} & b_{13} \\
    b_{21} & b_{22} & b_{23} \\
    b_{31} & b_{32} & b_{33}
    \end{bmatrix}
    =
    \begin{bmatrix}
    a_{11} b_{11} & a_{12} b_{12} & a_{13} b_{13} \\
    a_{21} b_{21} & a_{22} b_{22} & a_{23} b_{23} \\
    a_{31} b_{31} & a_{32} b_{32} & a_{33} b_{33}
    \end{bmatrix}
"""

display(Math(element_wise_product))

<IPython.core.display.Math object>

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

element_wise_product = a * b
print("Element-Wise Product:\n", element_wise_product)

Element-Wise Product:
 [ 4 10 18]
