In [44]:
from IPython.display import display, Math

# Inner Product

> 두 벡터 간 유사성을 구합니다.

In [45]:
inner_product = r"""
   \mathbf{a} \cdot \mathbf{b}
   = a_1 b_1 + a_2 b_2 + a_3 b_3
   = \sum_{i=1}^{n} a_i b_i
"""

display(Math(inner_product))

<IPython.core.display.Math object>

In [46]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

inner_product = np.dot(a, b)

print("Inner Product:\n", inner_product)

Inner Product:
 32


# Outer Product

> 행 벡터와 열 벡터의 곱으로 외적곱 행렬을 만듭니다.

In [47]:
outer_product = r"""
    \mathbf{a} \otimes \mathbf{b} =
    \begin{bmatrix}
    a_1 b_1 & a_1 b_2 & a_1 b_3 \\
    a_2 b_1 & a_2 b_2 & a_2 b_3 \\
    a_3 b_1 & a_3 b_2 & a_3 b_3
    \end{bmatrix}
"""

display(Math(outer_product))

<IPython.core.display.Math object>

In [48]:
a = np.array([1, 2, 3])
b = np.array([[4], [5], [6]])

outer_product = np.outer(a, b)

print("Outer Product:\n", outer_product)

Outer Product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


# Cross Product

> 두 벡터에 수직(orthogonal)한 벡터를 생성합니다.

In [49]:
cross_product = r"""
    \mathbf{a} \times \mathbf{b} =
    \begin{bmatrix}
    a_2 b_3 - a_3 b_2 \\
    a_3 b_1 - a_1 b_3 \\
    a_1 b_2 - a_2 b_1
    \end{bmatrix}
"""

display(Math(cross_product))

<IPython.core.display.Math object>

In [50]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

cross_product = np.cross(a, b)
print("Cross Product:\n", cross_product)


Cross Product:
 [-3  6 -3]
